// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Opciones predeterminadas de Firebase para usar con tus aplicaciones Firebase.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw _buildUnsupportedError('web');
    }

    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw _buildUnsupportedError('macos');
      case TargetPlatform.windows:
        throw _buildUnsupportedError('windows');
      case TargetPlatform.linux:
        throw _buildUnsupportedError('linux');
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions no son compatibles con esta plataforma.',
        );
    }
  }

  static UnsupportedError _buildUnsupportedError(String platform) {
    return UnsupportedError(
      'DefaultFirebaseOptions no han sido configuradas para $platform - '
      'puedes reconfigurar esto ejecutando FlutterFire CLI nuevamente.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCuxpkqIBJ9h6m83fOYZSX3ZTjFqRPLL3g',
    appId: '1:385397242544:android:5e07ca7030f38bb0bf5975',
    messagingSenderId: '385397242544',
    projectId: 'joby-eee06',
    storageBucket: 'joby-eee06.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAEeyLraag31w9ORJODkhs3wXjOi7wK7EM',
    appId: '1:385397242544:ios:ce299ed10281b0a9bf5975',
    messagingSenderId: '385397242544',
    projectId: 'joby-eee06',
    storageBucket: 'joby-eee06.appspot.com',
    iosClientId:
        '385397242544-e8kiepodl5hfhlmg6egj01j2ji3t81k6.apps.googleusercontent.com',
    iosBundleId: 'com.joby.loby',
  );
}
